#+TITLE: Git Explained
#+AUTHOR: Hoyoul Park
#+DESCRIPTION: Org-HTML export made simple.
#+KEYWORDS:  org-mode, export, html, theme, style, css, js, bigblow
#+LANGUAGE:  en
#+OPTIONS:   H:4 toc:t num:2
#+MACRO: color @@html:<font color=></font>@@
#+PROPERTY:  header-args :padline no
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+LATEX_HEADER: \usepackage{kotex}
#+latex_header: \hypersetup{colorlinks=true}

* Git 이란(Git의 본질)
** Git에 대한 오해와 바로잡음.
#+begin_note
*Git은 backup이 목적이 아니다.* Git을 사용하는 사람 중에서 git은 작업 history를 유지하기 때문에 지금 진행중이던 작업이 문제가 생겨서 과거의 특정 시점으로  되돌리기 위해서 사용한다고 생각할 수 있다. 물론 과거 특정시점으로 되돌릴 수 있다.  그러나 그렇게 되면 현재의 모든 commit을 잃게 된다. git은 backup을 목적으로 설계된게 아니기 때문이다. 왜냐면 git의  history는 과거의 commit을 가리키는 단방향 linked list로 되어 있어 있어서 현재의 위치를 나타내는 branch가 단방향 link로 가서 특정시점의 commit으로 이동해서 그때의 source code로 되돌릴 수는 있다. 그런데 이후의 작업 commit(저장본이라고 한다면)들은 접근할 수 없다. 물론 git의 설계가 그렇다는 것이다. commit은 hash로 표현되기 때문에 과거의 특정 commit으로 이동했어도 현재의 commit의 hash를 안다면 다시 돌아갈 수 있다. 그러나 그런 방식은 git에서 제공하는 facility가 아니다.
#+end_note
** version이란?
 #+begin_important
 git은 철저하게 program개발을 도와주는 infra tool이다. sw 개발을 도와주기 위한 목적이다. sw를 개발은 여러사람이 작업을 하며 공통된 source에서 기능을 하나 하나 추가해 나가는 개발방법을 따를때, 개발자들이 서로다른 source code로 작업을 할때 발생되는 code 불일치의 문제를 없애기 위해서 만들어졌다. 그래서 본래의 의도나 목적에 벗어나서 설명이 될 수 없다. git은 sw란 여러사람이 각자의 기능을 만들고 이를 합쳐서 version(완성된 program)이 나온다는 전제를 가지고 있다. version에서 미비하고 추가가 필요할때는 또 다시 여러 개발자가 개발을 하고 다시 통합해서 또 다른 version을 만든다.
 version은 완성된 program을 의미하며, 모든 개발자가 동일한 source code로 부터 개발을 시작할 수 있는 시작점이기도 하다. git은 개발자가 가진 다른 source code들을 합쳐주고, 동일한 code를 유지하는 기능이 주된 목적이라고 할 수 있다. git의 목적과 의도에 맞게 사용해야 한다. 이런 의도에서 주목할 만한 용어가 있다. 

- tracking: git은 동일한 source code를 유지하기 위해서 비교를 한다. 비교를 통해서만 update가 가능하고, update는 동일한 source code를 보장한다. 비교에는 기준이 되는 대상과 비교할 대상이 필요하다. 두 개의 대상은 항상 tracking되어야만 한다. 즉 changes가 발생할때, 그 changes 정보를 알고 있어야  한다는 뜻이다. 그것을 tracking이라고 한다.  예를 들어서 upstream의 A branch와 downstream에서 가지고 있는 A를 가리키는 remote branch가 서로 다른 commit을 가리키고 있다면 비교를 통해서 부족한 commit들을 download받아 update한다. 그러면 A를 가리키는 local의 remote branch는 update되어서 upstream의 A branch가 가리키는 commit과 동일한 local commit을 가리키게 되는데, 이렇게 changes를 유지하는게 tracking이다. 모든 branch는 changes를 유지하고 있기 때문에 tracking branch라고도 하고 원격에 있는 branch를 local에도 동일하게 유지하기 때문에 remote tracking branch라고도 부른다.
 #+end_important
** git의 본질(list)
* Git 사용(Local)
** git의 local사용에 대한 오해
#+begin_note
local에서 개인개발자 혼자 작업할때는 git이 그닥 필요 없을 수 있다. 왜냐 git의 목적은 개발자들이 가진 서로 다른 souce code를 합치는 중요한 기능을 사용하지 않기 때문이다. local에서 여러명의 개발자가 git을 사용한다면 문제는 없다.
#+end_note
* Git 사용(Remote) 
#+begin_note

#+end_note
